feat: init front
atls/kino-reporter pull request #40
Opened 2022-10-27 14:31 UTC by BRUSSELMINEFIVENINE

2022-11-04 12:52 UTC, TFK70 requested changes
Но вообще получилось круто, что в рендере, что в коде

2022-11-04 12:52 UTC, TFK70 commented on globals/data/package.json
> +  "name": "@globals/data",
globals === shared, это один и тот же скоуп. Помести это в shared

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/data/links/navigation-links.interface.ts
> +interface Data {
Data - это очень абстрактное название, его желательно избегать всегда и везде
LinkProperties или что-то в этом духе вполне сойдет

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/data/links/navigation-links.interface.ts
> +  data: {
Здесь тоже на мой взгляд data лишнее
Или я не прав?

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/promo-line/promo-line.component.tsx
> +          {[...new Array(50)].map(() => (
`[...new Array(50)]` - для этого лучше сделать специальный компонент в ui, типа `Repeater`. Я думаю, подобное можно даже в uikit вынести

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/search/helpers/use-filtered-data.hook.ts
> +  const filterBy = ({ title }) => {
filterBy... - фильтр по чему?

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/search/results/articles/articles.component.tsx
> +    {filteredArticles.slice(0, 3).map(({
А слайс для чего?

2022-11-04 12:52 UTC, TFK70 commented on site/app/fragments/header/src/search/results/results.component.tsx
> +        match={!!filteredFilms.length || !!filteredPersons.length || !!filteredArticles.length}
Вот эта двойная инверсия `!!` выглядит довольно страшно, как аналог предлагаю использовать Boolean(filteredFilms.length), это выглядит более читабельно

2022-11-04 12:52 UTC, TFK70 commented on ui/button/src/styles/base/base.styles.ts
> +  return () => ({
Для этого лучше используй utility функции `execAndSerialize` и `combine` из `@atls-ui-parts/styles`. Тип:

```javascript
return execAndSerialize(combine(baseStyles, textStyles, transitionStyles))
```

2022-11-04 12:52 UTC, TFK70 commented on ui/checkbox/src/checkbox.component.tsx
> +const doNothing = (...args) => {
Она же в `shared` есть

2022-11-04 12:52 UTC, TFK70 commented on ui/image/src/images/kino_reporter.image.ts
> +export default 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATcAAADpCAYAAABBYXDZAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAMjlSURBVHgB7H0FgCT1lf5X1S7jtjPr7oIvvliwYIGECAQI0
https://t.me/atls_lab/547

На VSBLE это использовалось тупо в качестве заглушки, в продовом варианте складывай все ассеты в public (у некста есть такая директория)

2022-11-04 17:19 UTC, carminio commented on site/app/fragments/header/src/search/results/articles/articles.component.tsx
> +    {filteredArticles.slice(0, 3).map(({
> А слайс для чего?

необходимо показывать только 3 элемента из всего массива

2022-11-04 17:23 UTC, carminio commented on site/app/fragments/header/src/data/links/navigation-links.interface.ts
> +  data: {
> Здесь тоже на мой взгляд data лишнее Или я не прав?

это синдром WP

2022-11-04 17:39 UTC, TFK70 requested changes

2022-11-04 17:39 UTC, TFK70 commented on site/app/fragments/header/src/dropdown-menu/dropdown-menu.component.tsx
> +              {links.links.drawer.map(({ title, path }, index) => (
о-о, `links.links` - такого точно быть не должно. Как так получилось?

У тебя либо приходит массив с общими данными где будет лежать links (типа data.links), либо сразу приходит links

2022-11-04 17:39 UTC, TFK70 commented on ui/utils/src/components/repeater/repeater.component.tsx
> +      {[...new Array(quantity)]?.map(onIteration)}
Я бы на твоем месте сделал так:

1. Убедился что `typeof children === 'function'`

```javascript
if (typeof children !== 'function') throw new Error('Repeater: children must be a function')
```

2. Вызывал бы на каждой итерации children:

```jsx
<Condition match={quantity === undefined}>{items?.map(children)}</Condition>
...
```

И на деле это было бы так:

```jsx
<Repeater quantity={7}>
   {() => <Text>Repeat me</Text>}
</Repeater>
```

2022-11-04 17:39 UTC, TFK70 commented on ui/utils/src/components/repeater/repeater.component.tsx
> +      {[...new Array(quantity)]?.map(onIteration)}
Это просто более православный путь в контексте реакта

2022-11-07 08:45 UTC, TFK70 approved these changes

2022-11-11 08:56 UTC, TorinAsakura requested changes

2022-11-11 08:56 UTC, TorinAsakura commented on site/app/fragments/header/src/search-mobile/search-mobile.component.tsx
> +              onKeyPress={handleKeyPress}
deprecated https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event

2022-11-11 13:41 UTC, TorinAsakura approved these changes

2022-11-11 13:42 UTC, merged