feat: films and serials
atls/kino-reporter pull request #47
Opened 2022-11-09 15:13 UTC by carminio

2022-11-10 08:53 UTC, TFK70 approved these changes

2022-11-10 19:54 UTC, TFK70 requested changes
Ещё баг заметили, в сафари у тебя текст пропадает на блоке с подборками, это происходит из-за смены opacity

Ты уверен что тут нужно опасити менять?

https://user-images.githubusercontent.com/62806448/201192773-e9f73f8a-5608-4594-9321-00de737c2b99.mov

2022-11-11 10:09 UTC, TFK70 approved these changes

2022-11-11 13:51 UTC, TorinAsakura approved these changes

2022-11-11 13:51 UTC, merged