Feat/newsletter
atls/kino-reporter pull request #48
Opened 2022-11-10 14:12 UTC by carminio

2022-11-10 19:26 UTC, TFK70 requested changes
И у тебя ещё почему-то 17 типы реакта на проекте стоят, хотя ты 18 юзаешь

На `"@types/react": "18.0.1"` если что всё стабильно

2022-11-10 19:26 UTC, TFK70 commented on site/app/fragments/newsletter/src/newsletter.component.tsx
> +  const weekly = description.slice(71)
Воу, это ведь, надеюсь, не продовое решение?

2022-11-10 21:04 UTC, carminio commented on site/app/fragments/newsletter/src/newsletter.component.tsx
> +  const weekly = description.slice(71)
> Воу, это ведь, надеюсь, не продовое решение?

Попробую завтра решить это разбитием строки на массив и там уже мапиться от этого массива и на условие определять цвета некоторым словам. 
Отсюда и вёрстка сократится и постабильнее будет выглядеть

2022-11-10 21:16 UTC, TFK70 commented on site/app/fragments/newsletter/src/newsletter.component.tsx
> +  const weekly = description.slice(71)
Ну и не забывай все эти дополнительные вычисления класть в useMemo, на будущее

2022-11-11 09:09 UTC, carminio commented
> И у тебя ещё почему-то 17 типы реакта на проекте стоят, хотя ты 18 юзаешь
> 
> На `"@types/react": "18.0.1"` если что всё стабильно

@TFK70 
Откатился на 17ю из-за typecheck в свайпере, https://github.com/nolimits4web/swiper/issues/5799

2022-11-11 11:54 UTC, TFK70 approved these changes

2022-11-11 13:52 UTC, TorinAsakura approved these changes

2022-11-11 13:53 UTC, merged